### ISSUE TITLE
Expected response code 250 but got code "530", with message "530 5.7.1 Authentication required "

### ISSUE THREAD

**Issue by Malemelo** [simioluwatomi/simple-referral#4]
D:\BookBasket Logos\bb_api\vendor\swiftmailer\swiftmailer\lib\classes\Swift\Transport\AbstractSmtpTransport.php
        }
    }
 
    /** Throws an Exception if a response code is incorrect */
    protected function assertResponseCode($response, $wanted)
    {
        if (!$response) {
            $this->throwException(new Swift_TransportException('Expected response code '.implode('/', $wanted).' but got an empty response'));
        }
 
        list($code) = sscanf($response, '%3d');
        $valid = (empty($wanted) || in_array($code, $wanted));
 
        if ($evt = $this->eventDispatcher->createResponseEvent($this, $response,
            $valid)) {
            $this->eventDispatcher->dispatchEvent($evt, 'responseReceived');
        }
 
        if (!$valid) {
            $this->throwException(new Swift_TransportException('Expected response code '.implode('/', $wanted).' but got code "'.$code.'", with message "'.$response.'"', $code));
        }
    }
 
    /** Get an entire multi-line response using its sequence number */
    protected function getFullResponse($seq)
    {
        $response = '';
        try {
            do {
                $line = $this->buffer->readLine($seq);
                $response .= $line;
            } while (null !== $line && false !== $line && ' ' != $line[3]);
        } catch (Swift_TransportException $e) {
            $this->throwException($e);
        } catch (Swift_IoException $e) {
            $this->throwException(new Swift_TransportException($e->getMessage(), 0, $e));
        }
 
        return $response;
    }
Arguments
"""
Expected response code 250 but got code "530", with message "530 5.7.1 Authentication required
"
"""

**Comment by simioluwatomi** [comment]
This is an error by `SwiftMailer`. What service are you using to send email? `SwiftMailer` is probably trying to authenticate with the service and it is failing.

**Comment by Malemelo** [comment]
Thank you, I have managed to correct the error
